# Site settings
name: 大家都叫我杰哥
location: 广东
company: OpenN
position: Golang开发
github: https://github.com/jageros
blog: https://blog.csdn.net/lhj_168
phone: 有事邮件联系我！
email: lhj168os@gmail.com

baseurl: "/resume"

permalink: /:year/:month/:day/:title/

exclude: ['README.md']

# Build settings
markdown: kramdown

